let wordBook_2017_001 =
{ "title": "혼동하기 쉬운 영어단어",
  "name": "wordBook_2017_001",
  "words": [
              {"word":"abate", "memo": "완화시키다, 누그러지다, 약해지다, 덜해지다, 줄이다"},
              {"word":"abject", "memo": "비열한, 비참한, 천한"},
              {"word":"abjure", "memo": "저버리다, …을 버리다, 부인하다, 취소하다, 회피하다"},
              {"word":"ablation", "memo": "제거, 삭마, 절제"},
              {"word":"able", "memo": "…할 수 있는, 유능한, 자격 있는, 수완 있는"},
              {"word":"abroad", "memo": "해외에, 외국에, 널리"},
              {"word":"abrogate", "memo": "폐기하다, 폐지하다, 무효화하다"},
              {"word":"abstruse", "memo": "난해한, 심오한"},
              {"word":"abundant", "memo": "풍부한, 많은, 과잉"},
              {"word":"accede", "memo": "동의하다, 가입하다, 받아들이다, 응하다, 오르다"},
              {"word":"accept", "memo": "받아들이다, 수용하다, 인정하다, 입학시키다, 응하다"},
              {"word":"acceptable", "memo": "받아들일 만한, 허용할 수 있는, 인정할 만한, 만족스러운, 참을 만한"},
              {"word":"access", "memo": "접근, 이용, 접속, 출입"},
              {"word":"accidental", "memo": "우발적인, 우연한, 사고로 인한, 실수로"},
              {"word":"acclamation", "memo": "환호성, 박수 갈채, 발성 투표"},
              {"word":"acquiescent", "memo": "묵묵히 따르는, 순종하는, 묵인하는"},
              {"word":"acquired", "memo": "습득한, 후천적인, 학습된"},
              {"word":"acrid", "memo": "신랄한, 매운, 쓴"},
              {"word":"activate", "memo": "…을 활동적이게 하다, 가동시키다, 활성화시키다"},
              {"word":"adapt", "memo": "…을 적응시키다, 순응하다, 개작하다"},
              {"word":"addiction", "memo": "중독, 과몰입, 빠짐, 의존, 몰두"},
              {"word":"adduce", "memo": "…을 제출하다, …을 인용하다, 인증하다"},
              {"word":"adjoin", "memo": "인접한, 붙어있는, 맞닿은, 주변, 연결하다"},
              {"word":"admission", "memo": "입학, 입장, 입원, 인정, 승인"},
              {"word":"adorn", "memo": "장식하다, 꾸미다, …의 아름다움을 돋보이게 하다"},
              {"word":"adroit", "memo": "능숙한, 교묘한, 솜씨있는"},
              {"word":"adventitious", "memo": "우발적인, 부정의, 외래의"},
              {"word":"adverse", "memo": "부정적인, 반대의, 불리한"},
              {"word":"advise", "memo": "조언하다, 권하다, 알리다, …하는 게 좋다, 상담하다"},
              {"word":"affect", "memo": "영향을 주다, 작용하다, 감염시키다, …체하다"},
              {"word":"affection", "memo": "애정, 애착, 사랑"},
              {"word":"affectionate", "memo": "애정 어린, 다정한"},
              {"word":"affinity", "memo": "친화성, 친밀감, 친, 애착, 유사점"},
              {"word":"afflict", "memo": "괴롭히다, 가하다, 지게 하다"},
              {"word":"afflux", "memo": "유입, 충혈, 흘러드는 것"},
              {"word":"aggression", "memo": "공격, 공격성, 침략"},
              {"word":"agility", "memo": "민첩, 민첩함, 민첩성"},
              {"word":"aid", "memo": "지원, 원조, 도움, 구호, 보조"},
              {"word":"ailment", "memo": "병, 질환, 불쾌"},
              {"word":"alike", "memo": "똑같이, 모두, 비슷한, 한결같이"},
              {"word":"alive", "memo": "살아 있는, 생기에 넘치는, 이 세상의, 계속하여, 생생한"},
              {"word":"allegation", "memo": "의혹, 혐의, 진술, 주장, 해명"},
              {"word":"allow", "memo": "…할 수 있게 하다, 허용하다, 허락하다"},
              {"word":"alloy", "memo": "합금, 합금하다, 섞다"},
              {"word":"allude", "memo": "암시하다, 언급하다, 넌지시 말하다"},
              {"word":"allusion", "memo": "암시, 언급, 넌지시 말함"},
              {"word":"alone", "memo": "혼자, 홀로, 다만 …뿐이다, 고립하여"},
              {"word":"altar", "memo": "제단, 분향소, 변기"},
              {"word":"alternate", "memo": "대체하다, 교류하다, 교대의, 번갈아 하다, 교차하다"},
              {"word":"altogether", "memo": "전적으로, 모두 함께, 합하여"},
              {"word":"amaze", "memo": "놀랍다, 멋진, 대단한 , 굉장한 , 훌륭한"},
              {"word":"amenable", "memo": "순종하는, 복종할 의무가 있는, 제재를 받는"},
              {"word":"amend", "memo": "개정하다, 수정하다, 보상"},
              {"word":"amity", "memo": "친선, 친목, 우호"},
              {"word":"amnesia", "memo": "기억 상실, 건망증, 기억상실증"},
              {"word":"anecdote", "memo": "일화"},
              {"word":"annual", "memo": "연간의, 연례의, 매년의, 연마다의, 해마다"},
              {"word":"anonymous", "memo": "익명의, 이름을 밝히지 않은, 무명, 어나니머스, 미상의"},
              {"word":"antique", "memo": "골동품, 옛날의"},
              {"word":"apathy", "memo": "냉담, 무관심, 무감각"},
              {"word":"apologia", "memo": "a formal written defense of something you believe in strongly"},
              {"word":"appealing", "memo": "매력적인, 마음을 끄는, 애원하는"},
              {"word":"appraise", "memo": "평가하다, 감정하다, 값을 매기다"},
              {"word":"apprehend", "memo": "…을 체포하다, 이해하다, 염려하다"},
              {"word":"arbitrary", "memo": "임의의, 독단적인, 제멋대로의"},
              {"word":"archaic", "memo": "고풍의, 원시적인, 낡은"},
              {"word":"argument", "memo": "주장, 논쟁, 말다툼, 논점, 논거"},
              {"word":"arouse", "memo": "불러일으키다, 일어서다, 분개하다, 각성시키다, 걱정시키다"},
              {"word":"arraign", "memo": "…을 규탄하다, 피고인에게 소인의 인부를 묻다, 책망하다"},
              {"word":"arrogant", "memo": "오만한, 거만한"},
              {"word":"arsonist", "memo": "a criminal who illegally sets fire to property"},
              {"word":"artful", "memo": "교활한, 교묘한, 기교 있는"},
              {"word":"artifact", "memo": "인공물, 인공 유물, 가공품"},
              {"word":"artistic", "memo": "예술적인, 미술적인"},
              {"word":"ascent", "memo": "오르기, 등반, 승진"},
              {"word":"ascetic", "memo": "금욕주의자, 금욕적인, 고행자"},
              {"word":"assemble", "memo": "조립하다, 모으다, 구성하다, 소집하다"},
              {"word":"assiduous", "memo": "근면한, 부지런한, 끈기 있는"},
              {"word":"assumed", "memo": "가장한, 꾸민, 겉꾸민"},
              {"word":"astronomer", "memo": "천문학자, 천문대장"},
              {"word":"astronomy", "memo": "천문학"},
              {"word":"atrophy", "memo": "위축, 쇠약, 위축시키다"},
              {"word":"attendance", "memo": "참석, 출석, 관객, 돌봄"},
              {"word":"audible", "memo": "들리는, 들을 수 있는, 목소리가 알아들을 수 있는"},
              {"word":"audit", "memo": "감사, 세무조사, 단속, 청강"},
              {"word":"aural", "memo": "청각의, 귀의, 영기의"},
              {"word":"autocratic", "memo": "독재적인, 전제의, 독재의"},
              {"word":"automation", "memo": "자동화"},
              {"word":"avocation", "memo": "부업, 취미, 여기"},
              {"word":"avoid", "memo": "피하다, 회피하다, 막다, 자제하다, 예방하다"},
              {"word":"awful", "memo": "끔찍한, 엄청난, 지독한, 심한, 이상한"},
              {"word":"bad", "memo": "나쁜, 좋지 않은, 잘못된, 심한, 상한"},
              {"word":"balmy", "memo": "향기로운, 온화한, 향유의"},
              {"word":"banal", "memo": "진부한, 평범한, 흔해빠진"},
              {"word":"bandage", "memo": "붕대, 밴드"},
              {"word":"banish", "memo": "추방하다, 떨쳐버리다"},
              {"word":"bare", "memo": "노출된, 드러내다, 극소량의, 벌거벗은, 단순한"},
              {"word":"barrage", "memo": "일제 엄호 사격, 연발, 탄막"},
              {"word":"base", "memo": "기반, 기초, 위치하다, …로 만든, 기지"},
              {"word":"bash", "memo": "강타하다, 강타, …을 두들겨 우그러뜨리다"},
              {"word":"bath", "memo": "목욕, 목욕물, 욕조, 욕실"},
              {"word":"bauble", "memo": "시시한 것, 겉만 번지르르한 싸구려 물건, 속 보이는 것"},
              {"word":"beatify", "memo": "시복하다, …을 더없이 행복하게 하다, 지복을 입게 하다"},
              {"word":"benediction", "memo": "축복, 감사 기도, 은총"},
              {"word":"beneficent", "memo": "자선심 많은, 선을 행하는, 선행을 하는"},
              {"word":"berth", "memo": "진출하다, 선석, 정박하다, 선실"},
              {"word":"beside", "memo": "곁에, 가, 벗어난, 비교하면"},
              {"word":"biannual", "memo": "1년에 두 번의, 반년 마다의, 2년에 한 번의"},
              {"word":"bilateral", "memo": "양국, 양자, 상호, 동맹, 쌍방"},
              {"word":"bizarre", "memo": "기괴한, 별난, 괴상한"},
              {"word":"blanch", "memo": "희게 하다, 살짝 데치다, …을 바래다"},
              {"word":"bland", "memo": "풍미없는, 개성없는, 단조로운, 지루한, 부드러운"},
              {"word":"blandish", "memo": "달콤한 말로 구슬리다, 알랑거리다, 구슬려서 시키다"},
              {"word":"bless", "memo": "축복하다, 감사하다, 지지하다"},
              {"word":"bloc", "memo": "블록, 연합, 세력권"},
              {"word":"blunt", "memo": "솔직한, 무딘, 퉁명스런, 둔화시키다"},
              {"word":"boast", "memo": "자랑하다, 가지고 있다, 뽐내다, 호언장담하다, 내세우다"},
              {"word":"bold", "memo": "힘있는, 과감한, 대담한, 용감한, 적극적"},
              {"word":"bombard", "memo": "폭격하다, 공격하다, …을 포격하다"},
              {"word":"bonny", "memo": "아름다운, 여자 이름, 훌륭한"},
              {"word":"border", "memo": "국경, 경계, 접해 있다, 인접하다, 가깝다"},
              {"word":"bored", "memo": "지루한, 싫증난"},
              {"word":"borrow", "memo": "빌리다, 대여하다, 차용하다, 빚지다"},
              {"word":"breach", "memo": "위반, 침해, 어기다, 무너지다, 누출"},
              {"word":"breath", "memo": "숨, 호흡, 냄새, 숨결"},
              {"word":"breed", "memo": "품종, 번식하다, 사육하다"},
              {"word":"bright", "memo": "밝은, 영리한, 빛나는, 긍정적인, 환한"},
              {"word":"brink", "memo": "직전, 위기, 벼랑"},
              {"word":"broke", "memo": "깼다, 부서졌다, 파산한, 무일푼의, 빈털터리의"},
              {"word":"bubble", "memo": "거품, 기포, 버블, 과열, 채우다"},
              {"word":"bullion", "memo": "금괴, 은괴, 금의 지금"},
              {"word":"bust", "memo": "흉상, 파산, 체포하다, 부수다, 상반신"},
              {"word":"cabal", "memo": "음모를 꾸미다, 음모단, 음모"},
              {"word":"calendar", "memo": "달력, 일정"},
              {"word":"calibrate", "memo": "눈금을 정하다, 눈금을 매기다, 구경을 측정하다"},
              {"word":"callous", "memo": "냉담한, 굳어진, 무감각한"},
              {"word":"cancel", "memo": "취소하다, 철회하다, 상쇄되다, 중지하다, 정지하다"},
              {"word":"candid", "memo": "솔직한, 진솔한, 자연스러운"},
              {"word":"cannon", "memo": "대포, 캐논, 허풍"},
              {"word":"canvas", "memo": "캔버스, 캔버스 천, 도화지"},
              {"word":"capacious", "memo": "널찍한, 많이 들어가는, 넓은"},
              {"word":"capital", "memo": "수도, 자본, 자금, 자산, 대문자"},
              {"word":"cardinal", "memo": "추기경, 기본적인, 카디널스"},
              {"word":"careless", "memo": "부주의한, 조심성 없는, 경솔한"},
              {"word":"carnal", "memo": "육체의, 육욕적인, 속세의"},
              {"word":"carnalize", "memo": "육욕에 빠지게 하다"},
              {"word":"carve", "memo": "조각하다, 차지하다, 자르다, 개척하다, 분할하다"},
              {"word":"castigate", "memo": "…을 혹평하다, 징계하다, 크게 책망하다"},
              {"word":"casualty", "memo": "사상자, 희생자, 피해자, 부상자"},
              {"word":"cataclysm", "memo": "대홍수, 정치적 대변동, 대변동"},
              {"word":"cave", "memo": "동굴, …에 굴을 파다, 움푹 들어가다"},
              {"word":"celerity", "memo": "민첩함, 민속, 민첩"},
              {"word":"censor", "memo": "검열, 금지, 통제, 감시, 삭제"},
              {"word":"ceremonial", "memo": "의식, 기념식, 식전, 형식적인, 정식의"},
              {"word":"cession", "memo": "양도, 양여, 할양"},
              {"word":"charlatan", "memo": "허풍선이, 협잡꾼, 돌팔이 의사"},
              {"word":"chart", "memo": "차트, 표, 수로도, 기록, 순위"},
              {"word":"chaste", "memo": "정숙한, 순결한, 고상한"},
              {"word":"childish", "memo": "유치한, 어린아이의"},
              {"word":"choral", "memo": "합창의, 합창으로 부르는"},
              {"word":"chord", "memo": "화음, 코드, 감정, 조화시키다"},
              {"word":"chronic", "memo": "만성의, 고질의, 장기적, 심각한 , 자주"},
              {"word":"cite", "memo": "예로 들다, 말하다, 소환하다"},
              {"word":"civic", "memo": "시민의, 민간, 도시의, 시빅"},
              {"word":"clap", "memo": "박수, 손뼉치다, 쿵하는 소리, 갈채, 성병"},
              {"word":"classic", "memo": "고전의, 클래식, 전형적인, 전통적인, 대표적인"},
              {"word":"climatic", "memo": "기후의, 기후에 의한"},
              {"word":"clinch", "memo": "매듭짓다, 클린치하다, 클린치"},
              {"word":"cloth", "memo": "천, 옷감, 직물, 걸레, 식탁보"},
              {"word":"coerce", "memo": "강요하다, 강요하여 시키다, 억압하다"},
              {"word":"cognitive", "memo": "인식의, 인지의, 인식력 있는"},
              {"word":"collision", "memo": "충돌, 전면전, 폭발"},
              {"word":"command", "memo": "명령하다, 사령부, 지휘하다, 명령을 내리다, 지시하다"},
              {"word":"commission", "memo": "위원회, 수수료, 의뢰, 권한, 사관"},
              {"word":"commodity", "memo": "상품, 원자재, 생필품"},
              {"word":"common", "memo": "공통의, 흔한, 일반적인, 공동의, 보통의"},
              {"word":"comparable", "memo": "비교할 만한, …에 비해, …와 비슷한, …에 해당하는"},
              {"word":"compassion", "memo": "동정, 연민, 측은하게 여기는 마음"},
              {"word":"complacent", "memo": "안주, 자기만족, 느긋한, 무관심한"},
              {"word":"complement", "memo": "보완하다, 전량"},
              {"word":"complexity", "memo": "복잡함, 난이도"},
              {"word":"component", "memo": "성분, 구성 요소, 부품, 컴포넌트 , 부분"},
              {"word":"comport", "memo": "행동하다, 처신하다, 어울리다"},
              {"word":"compound", "memo": "화합물, 복합의, 합성물, 혼합물, 복잡하다"},
              {"word":"comprehensible", "memo": "이해할 수 있는, 알기 쉬운, 알 수 있는"},
              {"word":"concede", "memo": "인정하다, 허용하다, 굴복하다"},
              {"word":"concept", "memo": "개념, 콘셉트, 생각, 정신, 의미"},
              {"word":"concerned", "memo": "우려하는, 관련된, 신경쓰는, 관심을 가진"},
              {"word":"condemn", "memo": "비난하다, 규탄하다, 유죄 판결을 내리다, 미워하다"},
              {"word":"conducive", "memo": "도움이 되는, 공헌하는, 이바지하는"},
              {"word":"conferment", "memo": "수여, 서훈"},
              {"word":"confidant", "memo": "절친한 친구, 친구, 믿을 만한 사람"},
              {"word":"confused", "memo": "혼란한, 헛갈리는, 당황한, 어리둥절한, 착각한"},
              {"word":"congenial", "memo": "같은 성질인, 성미와 맞는, 기분 좋은"},
              {"word":"conscious", "memo": "의식한, 친화적, 생각, 인식, 신경"},
              {"word":"conservative", "memo": "보수적인, 보수주의자, 보존, 우파, 수수한"},
              {"word":"considerate", "memo": "배려하는, 이해심이 있는, 관심을 가지다, 마음씨 좋은"},
              {"word":"console", "memo": "콘솔, 위로하다"},
              {"word":"constituent", "memo": "구성하는, 구성 요소, 성분"},
              {"word":"consul", "memo": "영사, 집정, 집정관"},
              {"word":"contagious", "memo": "전염성의, 감염병 , 파급"},
              {"word":"content", "memo": "콘텐츠, 내용, 함유량, 만족하는, 목차"},
              {"word":"contention", "memo": "논쟁, 말다툼, 주장"},
              {"word":"continence", "memo": "자제, 극기, 절제"},
              {"word":"continual", "memo": "계속적인, 끊임없는, 빈번한"},
              {"word":"contravene", "memo": "위반하다, 반대하다, 위반 행위를 하다"},
              {"word":"converge", "memo": "집중하다, …을 한 점에 모으다, 모이다"},
              {"word":"convert", "memo": "전환하다, 바꾸다, 개조하다, 개종하다, 득점하다"},
              {"word":"convey", "memo": "전달하다, 전하다, 나타내다, 의미하다"},
              {"word":"cook", "memo": "요리하다, 요리사, 만들다, 조리된, 쿡"},
              {"word":"cooperate", "memo": "협력하다, 협조하다, 협동하다"},
              {"word":"corps", "memo": "단체, 부대"},
              {"word":"corpse", "memo": "시체, 송장, 효력을 잃은 것"},
              {"word":"correspondent", "memo": "특파원, 기자, 일치하는"},
              {"word":"corroborate", "memo": "확증하다, 확실하게 하다, 확실히하다"},
              {"word":"country", "memo": "나라, 국가, 지역, 조국, 분야"},
              {"word":"cozy", "memo": "아늑한"},
              {"word":"crack", "memo": "균열, 크랙, 금 가다, 갈라지다, 시작하다"},
              {"word":"cramp", "memo": "경련, 쥐, …에 경련을 일으키다"},
              {"word":"crash", "memo": "충돌하다, 추락하다, 고장나다, 붕괴하다, 폭락"},
              {"word":"crave", "memo": "갈망하다, 열망하다, 간청하다, 갈구하다"},
              {"word":"credible", "memo": "신용할 수 있는, 확실한, 믿을 수 있는"},
              {"word":"critical", "memo": "비판적인, 중요한, 결정적인, 비평, 위험한"},
              {"word":"crutch", "memo": "목발, 버팀목, …을 버티다"},
              {"word":"curio", "memo": "골동품, 진품, 미술품"},
              {"word":"current", "memo": "현재의, 전류, 현행의, 지금의, 해류"},
              {"word":"custom", "memo": "세관, 관습, 풍습, 맞춤의, 문화"},
              {"word":"daily", "memo": "매일의, 일상적인, 데일리, 날마다"},
              {"word":"dearth", "memo": "부족, 결핍, 기근"},
              {"word":"decadent", "memo": "퇴폐적인, 퇴폐적인 사람, 쇠퇴기의"},
              {"word":"decease", "memo": "사망, 사망하다, 죽음"},
              {"word":"decent", "memo": "제대로 된, 품위있는, 좋은, 상당한"},
              {"word":"declivity", "memo": "내리받이, 경사, 하향경사"},
              {"word":"decolor", "memo": "탈색하다"},
              {"word":"decompose", "memo": "…을 분해하다, 부패하다, 분석하다"},
              {"word":"decorate", "memo": "장식하다, 꾸미다"},
              {"word":"deduce", "memo": "추론하다, 더듬다, 밝히다"},
              {"word":"deductive", "memo": "연역적인, 추리의"},
              {"word":"deem", "memo": "간주하다, 생각하다, 여기다"},
              {"word":"defective", "memo": "결함있는, 불량품, 불완전한"},
              {"word":"defendant", "memo": "피고의"},
              {"word":"defer", "memo": "연기하다, 결정을 맡기다, 경의를 표하다"},
              {"word":"deferment", "memo": "연기, 순연, 징병 연기"},
              {"word":"define", "memo": "정의하다, 말한다, 규정하다, 정하다, 의미"},
              {"word":"definite", "memo": "명확한, 분명한, 확실한, 명백한, 확정된"},
              {"word":"delegation", "memo": "대표단, 사절단, 위임, 대리"},
              {"word":"delighted", "memo": "기쁜, 즐거워하는"},
              {"word":"demonstrate", "memo": "증명하다, 입증하다, 시위하다, 나타내다, 설명하다"},
              {"word":"dent", "memo": "이, 살, 표면의 움푹한 곳"},
              {"word":"depend", "memo": "따라, 의존하다, 달리다, 의지하다, 좌우되다"},
              {"word":"dependent", "memo": "의존하는, 종속의, 의지하는, 부양 가족"},
              {"word":"deplete", "memo": "고갈시키다, 다 써버리다, 비우다"},
              {"word":"deplore", "memo": "한탄하다, 개탄하다, 슬퍼하다"},
              {"word":"deport", "memo": "추방하다, 강제 이송하다, 행동하다"},
              {"word":"depose", "memo": "폐, 물러나다, 퇴위시키다, 면직하다, 타도"},
              {"word":"deprecate", "memo": "비난하다, 반대하다, 전쟁따위를 반대하다"},
              {"word":"derelict", "memo": "유기된, 버려진, 직무 태만자"},
              {"word":"descry", "memo": "발견하다, …을 아득히 먼 곳에서 발견하다, 찾아내다"},
              {"word":"desert", "memo": "사막, 버리다, 비우다, 탈영하다, 황무지"},
              {"word":"desirable", "memo": "바람직한"},
              {"word":"desperate", "memo": "필사적인, 절실한, 절망적인, 자포자기의, 극도의"},
              {"word":"despotism", "memo": "압제, 독재, 전제 정치"},
              {"word":"desultory", "memo": "일관성 없는, 산만한, 종잡을 수 없는"},
              {"word":"detract", "memo": "딴 데로 돌리다, 줄이다, 손상시키다"},
              {"word":"devise", "memo": "고안하다, 마련하다, 만들어내다, 계획, 방법"},
              {"word":"die", "memo": "죽다, 사망하다, 사라지다, 떠나다, 꺼지다"},
              {"word":"different", "memo": "다른, 여러 가지의, 종류, 별개의, 독특한"},
              {"word":"diffuse", "memo": "퍼뜨리다, 보급하다, 방산하다"},
              {"word":"dilate", "memo": "…을 팽창시키다, 넓히다, 넓어지다"},
              {"word":"diplomacy", "memo": "외교, 외교적 수완, 외교술"},
              {"word":"disappoint", "memo": "실망시키다, 낙담시키다, 기대에 어긋나다, 망치다"},
              {"word":"disapprove", "memo": "반대하다, 못마땅해하다"},
              {"word":"disassemble", "memo": "분해되다, 해체하다, 해산, 역어셈블, 와해"},
              {"word":"discard", "memo": "버리다, 폐기, 포기, 가치없는 , 처리"},
              {"word":"disciple", "memo": "제자, 문하생, 신봉자"},
              {"word":"discreet", "memo": "신중한, 분별력 있는, 사려깊은"},
              {"word":"disinterested", "memo": "공평한, 관심이 없는, 사심 없는"},
              {"word":"disjoin", "memo": "분리하다, …을 떼다, 분리되다"},
              {"word":"dispatch", "memo": "파견, 파병, 급파, 보내다, 배치"},
              {"word":"dissent", "memo": "반대, 이의, 항의, 다른, 이견"},
              {"word":"dissolution", "memo": "해산, 붕괴"},
              {"word":"distinct", "memo": "뚜렷한, 다른, 독특한"},
              {"word":"distribution", "memo": "분포, 분배, 유통, 배포, 배급"},
              {"word":"diverse", "memo": "다양한, 여러 가지의, 다른, 광범위한, 각계 각층의"},
              {"word":"diversion", "memo": "전환, 유용, 딴 데로 돌림"},
              {"word":"docile", "memo": "가르치기 쉬운, 다루기 쉬운, 유순한"},
              {"word":"domestic", "memo": "국내의, 내수, 가정의, 국산의, 자국의"},
              {"word":"dose", "memo": "복용, 1회분, 약간의"},
              {"word":"dramatic", "memo": "극적인, 급격한, 인상적인, 드라마틱한, 연극의"},
              {"word":"drought", "memo": "가뭄, 한발, 고갈"},
              {"word":"dual", "memo": "이중의, 이원적인, 양수"},
              {"word":"dub", "memo": "찌르다, …이라고 부르다, 재녹음"},
              {"word":"dubious", "memo": "의심스러운, 반신반의하는, 모호한"},
              {"word":"duplicate", "memo": "중복되다, 복제한, 같은 , 복사하다, 이중"},
              {"word":"dwindle", "memo": "점점 작아지다, 줄어들다, 쇠퇴하다"},
              {"word":"eclipse", "memo": "식, 가리다, 이클립스, 에클리제, 상쇄"},
              {"word":"economy", "memo": "경제, 경기, 이코노미"},
              {"word":"edict", "memo": "칙령, 포고, 명령"},
              {"word":"effective", "memo": "효과적인, 효율적인, 효력있는, 유효한, 유능한"},
              {"word":"elder", "memo": "노인, 어른, 연장자, 장로, 고참"},
              {"word":"elective", "memo": "선거의, 선택 과목, 선거로 임용되는"},
              {"word":"elemental", "memo": "자연력의, 기본적인, 요소의"},
              {"word":"elicit", "memo": "이끌어 내다, 끌어내다, 유도해 내다"},
              {"word":"eligible", "memo": "자격이 있는, 권한이 있는, 가능한"},
              {"word":"emaciate", "memo": "…을 야위게 하다, 야위다, 약하게 하다"},
              {"word":"emanate", "memo": "발산하다, 나오다, 퍼지다"},
              {"word":"embarrassed", "memo": "부끄러운, 당황한, 당혹스러운"},
              {"word":"emerge", "memo": "떠오르다, 새로운, 나타나다, (어려움에서) 벗어나다, 명백해지다"},
              {"word":"emigration", "memo": "이민, 이주, 이주자"},
              {"word":"eminent", "memo": "저명한, 탁월한"},
              {"word":"employee", "memo": "직원, 직장인, 근로자, 종업원, 고용인"},
              {"word":"endemic", "memo": "풍토병, 지방병, 특유한"},
              {"word":"endue", "memo": "…을 입다, …에게 부여하다, …인 체하다"},
              {"word":"enormity", "memo": "심각함, 영향력의 거대함, 잔학무도한 행위"},
              {"word":"ensure", "memo": "…하기 위해, 보장하다, 확보하다, 확실하게 하다"},
              {"word":"entomology", "memo": "곤충학"},
              {"word":"envelop", "memo": "싸다, 봉하다, …을 덮다"},
              {"word":"envisage", "memo": "…을 마음에 그리다, 상상하다, 예상하다"},
              {"word":"epidemic", "memo": "유행, 유행병, 유행성의"},
              {"word":"equitable", "memo": "공정한, 공평한, 정당한"},
              {"word":"erode", "memo": "침식하다, 부식하다, 부식되다"},
              {"word":"erratic", "memo": "변덕스러운, 별난, 괴짜"},
              {"word":"esoteric", "memo": "비밀의, 심원한, 난해한"},
              {"word":"especially", "memo": "특히, 더욱, 두드러지게, 유달리"},
              {"word":"ethnic", "memo": "민족의, 혈통의, 인종의, 종족"},
              {"word":"euphony", "memo": "듣기 좋은 어조, 음조가 좋음, 듣기좋은 소리"},
              {"word":"eventual", "memo": "최후의, 궁극적인, 언젠가는 일어나는"},
              {"word":"everyday", "memo": "매일의, 일상의, 평소의"},
              {"word":"exactly", "memo": "정확히, 그렇소, 바로, 확실히, 딱"},
              {"word":"exalt", "memo": "높이다, …을 칭찬하다, 강화하다"},
              {"word":"excite", "memo": "흥분시키다, 신나게 하다, 들뜨게 하다, 기대하게 만들다, 흥미롭게 하다"},
              {"word":"exciting", "memo": "흥미진진한, 신나는, 재미있는, 흥분시키는, 놀라운"},
              {"word":"excrement", "memo": "배설물, 대변"},
              {"word":"excrete", "memo": "배설하다, 분비하다, 방출하다"},
              {"word":"exhausted", "memo": "다 써버린, 소모된, 기진맥진한"},
              {"word":"expand", "memo": "확대하다, 확장하다, 늘다, 성장하다, 넓히다"},
              {"word":"exposure", "memo": "노출, 폭로, 유기, 방향, 드러남"},
              {"word":"extend", "memo": "확장하다, 연장하다, 늘리다, 미치다, 뻗다"},
              {"word":"factitious", "memo": "꾸며낸, 인공적인, 인위적인"},
              {"word":"faint", "memo": "희미한, 기절하다, 거의"},
              {"word":"fair", "memo": "공정한, 공평한, 박람회, 전시회, 타당한"},
              {"word":"famine", "memo": "기근, 기아, 굶주림"},
              {"word":"famous", "memo": "유명한, 잘 알려진, 뛰어난, 훌륭한, 멋진"},
              {"word":"farther", "memo": "더 멀리, 더 나아가서, 더욱, 그 이상의"},
              {"word":"favor", "memo": "부탁, 선호하다, 주다, 찬성하다, 호의"},
              {"word":"feat", "memo": "위업, 공적, 묘기"},
              {"word":"feign", "memo": "…인 체하다, 가장하다, 꾸며대다"},
              {"word":"female", "memo": "여성의, 여자의, 암컷의"},
              {"word":"fertile", "memo": "비옥한, 가임의, 다산의"},
              {"word":"few", "memo": "몇몇의, 거의 없는, 소수의, 소수의 사람, 약간의"},
              {"word":"fickle", "memo": "변덕스러운, 변하기 쉬운, 진심이 없는"},
              {"word":"fictitious", "memo": "허구의, 거짓의, 가공의"},
              {"word":"fidget", "memo": "안절부절못하다, 안달나게 하다, 조바심내다"},
              {"word":"find", "memo": "찾다, 발견하다, 알다, 알아보다"},
              {"word":"finesse", "memo": "솜씨, 기교, 수완, 피네스"},
              {"word":"fitting", "memo": "적절한, 꼭 맞는, 어울리는, 꽉 끼는"},
              {"word":"flagrant", "memo": "악명 높은, 극악한, 명백한"},
              {"word":"flake", "memo": "얇은 조각, 플레이크, 눈, 벗겨지다, 속이다"},
              {"word":"flame", "memo": "화염, 불꽃, 타오르다, 불태우다, 애인"},
              {"word":"flank", "memo": "측면, 옆구리, …의 측면을 우회하다"},
              {"word":"flare", "memo": "플레어, 확 타오르다, 나팔꽃 모양으로 벌어지다"},
              {"word":"flatter", "memo": "아첨하다, 납작해지다, 자만하다, 돋보이게 하다"},
              {"word":"flaunt", "memo": "과시하다, 자랑하다"},
              {"word":"flaw", "memo": "결점, 흠, 결함"},
              {"word":"flesh", "memo": "살, 피부, 고기, 육체, 육식"},
              {"word":"flight", "memo": "비행기, 비행, 항공편, 여행, 도피"},
              {"word":"florescent", "memo": "개화한, 전성기의, 꽃이 핀"},
              {"word":"flounder", "memo": "몸부림치다, 허우적거리다, 허둥대다"},
              {"word":"forage", "memo": "사료, 먹이, 채집하다, 식량, 찾아다니다"},
              {"word":"forbear", "memo": "억제하다, 참고 견디다, 참다"},
              {"word":"forceful", "memo": "강제적인, 강력한, 설득력 있는"},
              {"word":"forego", "memo": "앞서다, 앞에 가다, …에 선행하다"},
              {"word":"formerly", "memo": "이전에, 옛날에는, 원래는"},
              {"word":"fortuitous", "memo": "우연한, 뜻밖의, 우발성의"},
              {"word":"foul", "memo": "나쁜, 파울, 욕설, 반칙, 실패하다"},
              {"word":"fraction", "memo": "일부, 적은, 분수, 파편"},
              {"word":"fragile", "memo": "취약한, 깨지기 쉬운, 부진한, 쉽게 영향을 받는"},
              {"word":"fraud", "memo": "사기, 분식, 부정, 조작, 위조"},
              {"word":"freeze", "memo": "동결, 냉동하다, 얼다, 추워지다, 멈추다"},
              {"word":"frightened", "memo": "두려움을 느끼는, 깜짝 놀란, 겁을 먹은, 무서워하는, 떠는"},
              {"word":"fudge", "memo": "…을 날조하다, 퍼지, 대체 기사"},
              {"word":"fun", "memo": "재미있는, 즐거운, 놀리다, 신나는, 장난"},
              {"word":"function", "memo": "기능, 역할, 작동, 작용, 행사"},
              {"word":"gamble", "memo": "도박하다, 모험하다, …을 걸다"},
              {"word":"garner", "memo": "…을 모으다"},
              {"word":"gasp", "memo": "숨이 차다, 헐떡거리다"},
              {"word":"gem", "memo": "보석, 보물"},
              {"word":"gene", "memo": "유전자"},
              {"word":"generic", "memo": "일반적인, 포괄적인, 총칭적인"},
              {"word":"genteel", "memo": "품위 있는, 가문이 좋은, 점잖은 체하는"},
              {"word":"genuine", "memo": "진실된, 진짜의, 순수한, 성실한"},
              {"word":"german", "memo": "독일, 독일어, 독일인, 게르만"},
              {"word":"ghastly", "memo": "무시무시한, 지독한, 무섭게"},
              {"word":"gingerly", "memo": "매우 신중하게, 아주 신중하게, 지극히 조심스럽게"},
              {"word":"gist", "memo": "요점, 골자, 요지"},
              {"word":"globe", "memo": "세계, 지구, 글로브, 구, 세상"},
              {"word":"gorge", "memo": "폭식, 골짜기, 협곡"},
              {"word":"grateful", "memo": "감사하는, 고마운"},
              {"word":"grim", "memo": "우울한, 냉혹한, 어두운, 으스스한"},
              {"word":"grisly", "memo": "무서운, 소름 끼치는, 끔찍하게"},
              {"word":"gross", "memo": "총, 전체, 역겹다, 징그럽다, 더럽다"},
              {"word":"ground", "memo": "지상의, 땅, 기반, 영역, 기본의"},
              {"word":"gully", "memo": "도랑, 도랑을 만들다, 만들다"},
              {"word":"habitat", "memo": "서식지, 생태, _지, 살다, 해비타트"},
              {"word":"hallow", "memo": "…을 신성하게 하다, 성직자, hallo(이봐)"},
              {"word":"haphazard", "memo": "되는 대로의, 우연의, 우연히"},
              {"word":"hard", "memo": "열심히, 어려운, 힘든, 강경한, 고생"},
              {"word":"haughty", "memo": "오만한, 거만한, 건방진"},
              {"word":"heal", "memo": "치유되다, 치료하다, 낫다, 효능이 있다."},
              {"word":"healthy", "memo": "건강한, 건강에 좋은, 건전한, 위생적인, 유익한"},
              {"word":"hear", "memo": "듣다, 소식을 듣다, 경청하다"},
              {"word":"heckle", "memo": "당돌한 질문으로 애먹이다, 괴롭히다, 야유를 퍼붓다"},
              {"word":"hefty", "memo": "크고 튼튼한, 커서 움직이기 어려운, 육중한"},
              {"word":"heirless", "memo": "상속인이 없는, 계승자가 없는"},
              {"word":"helm", "memo": "조타 장치, 타각, 중세 초기의 투구"},
              {"word":"historic", "memo": "역사적인, 사"},
              {"word":"hitch", "memo": "매기, 걸기, …을 결혼시키다"},
              {"word":"hoard", "memo": "…을 저장하다, 축적, 저장"},
              {"word":"holiday", "memo": "휴일, 명절, 공휴일, 휴가, 축제일"},
              {"word":"horn", "memo": "경적, 뿔, 호른"},
              {"word":"hostile", "memo": "적대적인, 호전적인, 적의, 강경한, 부적당한"},
              {"word":"humane", "memo": "인도적인"},
              {"word":"hustle", "memo": "기운차게 하기, 서두르다, 밀다"},
              {"word":"hyperbole", "memo": "과장, 과장법, 과장적 서술"},
              {"word":"hypercritical", "memo": "흠을 들추어내는, 비판이 지나치게 엄한, 혹평적인"},
              {"word":"hypertension", "memo": "고혈압, 과도의 긴장, 고혈압증"},
              {"word":"hypothesis", "memo": "가설, 가정, 추측"},
              {"word":"ideal", "memo": "이상적인, 이념적인, 관념적인"},
              {"word":"illuminate", "memo": "밝게하다, 부각되다, 명확히 하다, 미소짓다, 눈부시게 꾸미다"},
              {"word":"imaginary", "memo": "상상의, 가상의, 가식적인"},
              {"word":"imminent", "memo": "절박한, 임박한, 일촉즉발의"},
              {"word":"immoral", "memo": "비도덕적, 부도덕한, 부당한"},
              {"word":"immunity", "memo": "면제, 면역, 면책"},
              {"word":"impart", "memo": "주다, 알리다, 전하다"},
              {"word":"impassive", "memo": "감정이 없는, 태연한, 무감동의"},
              {"word":"impediment", "memo": "장애, 방해, 언어 장애"},
              {"word":"imperil", "memo": "위태롭게 하다, 위험에 빠뜨리다, 위험하게 하다"},
              {"word":"impertinent", "memo": "건방진, 불손한, 엉뚱한, 무례한"},
              {"word":"impetus", "memo": "자극, 기동력, 힘"},
              {"word":"implacable", "memo": "무자비한, 달래기 어려운, 앙심 깊은"},
              {"word":"implicit", "memo": "은연중의"},
              {"word":"important", "memo": "중요한, 주요한, 중대한, 소중한"},
              {"word":"imposing", "memo": "웅장한, 인상적인, 눈을 끄는"},
              {"word":"impractical", "memo": "비현실적인, 비실용적인"},
              {"word":"impression", "memo": "인상, 생각, 흉내"},
              {"word":"imprudent", "memo": "경솔한, 무분별한, 무모한"},
              {"word":"impunity", "memo": "무사, 형벌을 받지 않음, 형벌을 면하기"},
              {"word":"inane", "memo": "어리석은, 무의미한, 공허한"},
              {"word":"inapt", "memo": "부적당한, 적절치 않은, 서투른"},
              {"word":"incident", "memo": "사건, 사고, 사태, 사변"},
              {"word":"incredible", "memo": "엄청난, 놀라운, 믿을 수 없는"},
              {"word":"inculcate", "memo": "가르치다, 주입시키다, 타이르다"},
              {"word":"incumbent", "memo": "현직의, 현직자, 재직자"},
              {"word":"indict", "memo": "기소하다, 비난하다, 공격하다"},
              {"word":"indigenous", "memo": "고유의, 토착의, 고유한"},
              {"word":"indiscriminate", "memo": "무차별의, 닥치는 대로의, 분간 없는"},
              {"word":"indolent", "memo": "게으른, 나태한, 게으름쟁이의"},
              {"word":"induce", "memo": "유발하다, 유도하다, 유치하다, 유인하다, …하게 하다"},
              {"word":"industrious", "memo": "부지런한, 근면한, 노력하는"},
              {"word":"infinite", "memo": "무한한, 끝없는, 인피니트 , 무수한 , 무궁한"},
              {"word":"inflammable", "memo": "불붙기 쉬운, 인화성의, 격앙하기 쉬운"},
              {"word":"infringe", "memo": "침해하다, 어기다, 위반하다"},
              {"word":"ingenious", "memo": "독창적인, 재치있는, 교묘한"},
              {"word":"ingredient", "memo": "재료, 성분"},
              {"word":"initial", "memo": "초기의, 원래의, 1차, 첫 글자, 선도하는"},
              {"word":"inject", "memo": "…을 주입하다, 주사하다, 삽입하다"},
              {"word":"innumerable", "memo": "셀 수 없이 많은, 무수한"},
              {"word":"insoluble", "memo": "해결할 수 없는, 용해되지 않는, 녹지 않는"},
              {"word":"insulation", "memo": "절연체, 단열재, 절연 상태"},
              {"word":"intelligent", "memo": "지능이 있는, 지적인, 똑똑한, 총명한"},
              {"word":"intension", "memo": "강도, 긴장, 격렬함"},
              {"word":"interesting", "memo": "흥미로운, 재미있는, 놀라운"},
              {"word":"intimate", "memo": "친밀한, 사적인, 은밀한, 개인적인, 암시하다"},
              {"word":"intimidate", "memo": "…을 두려워하게 하다, …을 협박하다, 겁먹게 하다"},
              {"word":"invaluable", "memo": "매우 귀중한, 헤아릴 수 없을 만큼 귀중한"},
              {"word":"invidious", "memo": "불공평한, 비위에 거슬리는, 시샘나게 하는"},
              {"word":"itinerary", "memo": "일정, 기행, 여행, 여정"},
              {"word":"jaunty", "memo": "경쾌한, 쾌활한, 말쑥한"},
              {"word":"jealous", "memo": "질투하는, 시기하는, 부러워하는, 탐내는"},
              {"word":"jot", "memo": "…을 간결하게 적다, 간단히 메모하다, 아주 조금"},
              {"word":"journal", "memo": "정기 간행물, 저널, 일기, 잡지"},
              {"word":"judicial", "memo": "사법의, 재판의, 재판상의"},
              {"word":"knave", "memo": "부정직한 사람, 악한, 카드놀이의 잭"},
              {"word":"kneel", "memo": "무릎을 꿇다, 굴복하다"},
              {"word":"laborious", "memo": "근면한, 힘드는, 어려운"},
              {"word":"lapse", "memo": "시간이 경과하다, 실패, …상태로 빠지다, 잘못"},
              {"word":"late", "memo": "말기의, 늦은, 늦도록, 늦게, 최근의"},
              {"word":"later", "memo": "후에, 나중에, 말, 지나, 뒤에"},
              {"word":"latitude", "memo": "위도, 허용 범위, 자유"},
              {"word":"laud", "memo": "찬송가"},
              {"word":"lay", "memo": "낳다, 눕다, 놓다, 마련하다, 쌓다"},
              {"word":"legal", "memo": "법적인, 법률상의, 합법적인"},
              {"word":"lessen", "memo": "줄이다, 완화하다, 감소하다"},
              {"word":"liberal", "memo": "진보적인, 자유로운, 자유주의의, 개방적인, 관대한"},
              {"word":"light", "memo": "빛, 밝게하다, 조명, 광선, 가벼운"},
              {"word":"likelihood", "memo": "가능성, 기회, 가망"},
              {"word":"limb", "memo": "팔다리, 의족, 가지"},
              {"word":"literal", "memo": "글자 그대로의, 문자의"},
              {"word":"little", "memo": "작은, 조금, 좀, 약간의, 어린"},
              {"word":"locale", "memo": "장소, 현장, 무대"},
              {"word":"loose", "memo": "느슨해지다, 풀다, 헐거운, 엉성한, 자유로운"},
              {"word":"loot", "memo": "약탈하다, 전리품, 돈"},
              {"word":"loyal", "memo": "충성스러운, 충실한, 지지하는, 충직한, 성의 있는"},
              {"word":"lucrative", "memo": "수익성, 많은 돈이 되는, 이득, 호황, 수완이 좋은"},
              {"word":"lustrous", "memo": "번쩍이는, 빛나는, 저명한"},
              {"word":"luxuriant", "memo": "풍부한, 무성한, 화려한"},
              {"word":"magnificent", "memo": "멋진, 아름다운, 훌륭한, 웅장한, 장엄한"},
              {"word":"male", "memo": "남성, 수컷, 말레"},
              {"word":"malleable", "memo": "두들겨 펼 수 있는, 두드려 펼 수 있는, 가단성의"},
              {"word":"manor", "memo": "영지, 영주의 저택, 본채"},
              {"word":"mar", "memo": "망쳐놓다, 흠가게 하다, 훼손하다"},
              {"word":"marital", "memo": "부부의, 결혼의, 혼인의, 가족의, 남편의"},
              {"word":"marvel", "memo": "경이로움, 경탄하다, 놀라다"},
              {"word":"mass", "memo": "대량의, 질량, 대중의, 집단의, 미사"},
              {"word":"masterful", "memo": "명인 솜씨의, 대가의, 오만한"},
              {"word":"material", "memo": "재료, 자료, 물질의, 소재, 성분"},
              {"word":"matriarch", "memo": "가모장, 수령격의 여자, 여가장"},
              {"word":"maul", "memo": "거칠게 다루다, 큰 망치, …을 난폭하게 다루다"},
              {"word":"mediate", "memo": "매개, 영향, 이용하다, 중재하다, 조정하다"},
              {"word":"memory", "memo": "something that is remembered"},
              {"word":"menial", "memo": "하인, 머슴, 비천한"},
              {"word":"meretricious", "memo": "저속한, 음란한, 야한"},
              {"word":"message", "memo": "메시지, 말씀, 교훈, 전갈, 문구"},
              {"word":"metabolism", "memo": "신진대사, 물질 대사, 대사"},
              {"word":"migrate", "memo": "이동하다, 이주하다"},
              {"word":"mince", "memo": "잘게 썰다, 다지다, 뽐내며 종종걸음으로 걷다"},
              {"word":"minute", "memo": "분, 잠깐, 적은 양의, 의사록"},
              {"word":"miserly", "memo": "인색한, 욕심 많은, 수전노인"},
              {"word":"mitigate", "memo": "완화하다, 줄이다, 저감, 경감, 덜어주다"},
              {"word":"moan", "memo": "신음, 한탄하다, 불평, 끙끙거리다"},
              {"word":"momentous", "memo": "중요한, 중대한, 비상한"},
              {"word":"momentum", "memo": "모멘텀, 운동량, 탄력, 힘, 추진력"},
              {"word":"monarchy", "memo": "군주제, 왕조"},
              {"word":"monetary", "memo": "통화의, 금융의, 금전의, 화폐의, 재정의"},
              {"word":"morale", "memo": "사기, 의욕, 모랄레스, 윤리, 도덕"},
              {"word":"mortgage", "memo": "주택 담보 대출, 모기지, 융자"},
              {"word":"mug", "memo": "습격하다, 과장된 표정을 짓다, 컵"},
              {"word":"negligible", "memo": "하찮은, 무시해도 좋은, 무시할만한"},
              {"word":"nemesis", "memo": "천벌, 네메시스, 응보"},
              {"word":"noted", "memo": "유명한, 저명한, 현저한"},
              {"word":"notify", "memo": "통보하다, 알리다, 신고하다, 발표하다"},
              {"word":"object", "memo": "물건, 객체, 것, 대상, 목적"},
              {"word":"oblique", "memo": "비스듬한, 사선의, 사격의"},
              {"word":"obsequious", "memo": "아첨하는, 알랑거리는, 아부하는"},
              {"word":"observance", "memo": "준수, 식전, 관습"},
              {"word":"obvious", "memo": "분명한, 명백한, 뻔한, 확실한"},
              {"word":"officious", "memo": "비공식의, 참견하기 좋아하는, 주제넘게 나서는"},
              {"word":"opposed", "memo": "대항하는, 반대의, 적대적인"},
              {"word":"opulence", "memo": "풍부, 부유, 현란"},
              {"word":"orbit", "memo": "궤도, 돌다, 안구"},
              {"word":"ordinance", "memo": "법령, 조례, 규정"},
              {"word":"organism", "memo": "생물, 유기체, 인간, 생체"},
              {"word":"orthodox", "memo": "정교회, 정통의, 전통적인"},
              {"word":"ostensible", "memo": "표면상의, 겉보기만의, 표면만의"},
              {"word":"pack", "memo": "싸다, 꽉 들어찬, 갑, 채우다, 짐"},
              {"word":"pact", "memo": "조약, 협정, 약속"},
              {"word":"palpable", "memo": "명백한, 만질 수 있는, 촉진할 수 있는"},
              {"word":"panacea", "memo": "만병통치약, 만능약"},
              {"word":"paramount", "memo": "최고의, 주요한, 군주"},
              {"word":"parch", "memo": "볶다, 굽다, 바싹 마르다"},
              {"word":"pathetic", "memo": "불쌍한, 한심한, 슬픈"},
              {"word":"pedestrian", "memo": "보행의, 도보의, 평범한"},
              {"word":"peerless", "memo": "비길 데 없는, 무쌍의, 무류의"},
              {"word":"percentage", "memo": "포인트, 비율, 퍼센트, 부분, 퍼센티지"},
              {"word":"percolate", "memo": "…에 삼투하다, 여과하다, 거르다"},
              {"word":"perimeter", "memo": "경계, 주변, 외곽"},
              {"word":"perish", "memo": "사라지다, 죽다"},
              {"word":"permissible", "memo": "허용되는, 무방한, 소지가 허가된"},
              {"word":"perpetuate", "memo": "…을 영속하게 하다, 불후하게 하다, 영존시키다"},
              {"word":"persecute", "memo": "박해하다, 고통받다, 처벌하다"},
              {"word":"personal", "memo": "개인의, 자신의, 사적인, 인간적인, 자기의"},
              {"word":"personality", "memo": "성격, 사람, 인성, 개성, 인격"},
              {"word":"perspective", "memo": "관점, 시각, 전망, 견해, 원근법"},
              {"word":"perspicuous", "memo": "명료한, 명쾌한, 분명한"},
              {"word":"pertinent", "memo": "적절한, 관계가 있는, 부속물"},
              {"word":"perverse", "memo": "심술궂은, 사악한, 기대에 어긋나는"},
              {"word":"pester", "memo": "난처하게 만들다, 방해하다, 괴롭히다"},
              {"word":"petrify", "memo": "석화하다, 망연자실하게 하다, …을 굳어지게 하다"},
              {"word":"phony", "memo": "가짜인, 가짜, 위조품"},
              {"word":"physician", "memo": "의사"},
              {"word":"piece", "memo": "조각, 작품, 부분, 하나, 일부"},
              {"word":"pile", "memo": "쌓다, 더미, 모으다, 저축하다"},
              {"word":"plague", "memo": "전염병, 괴롭히다, 페스트, 시달리다, 골치를 앓다"},
              {"word":"polite", "memo": "예의 바른, 공손한, 정중한"},
              {"word":"ponderous", "memo": "대단히 무거운, 다루기 힘든, 크고 무거운"},
              {"word":"pool", "memo": "수영장, 풀, 모으다, 당구"},
              {"word":"popular", "memo": "인기 있는, 유명한, 대중의, 국민의"},
              {"word":"portable", "memo": "휴대용의, 이동식, 포터블"},
              {"word":"portent", "memo": "전조, 조짐, 경이적인 존재"},
              {"word":"pose", "memo": "포즈, 제기하다, 가하다, 주장하다, 야기하다"},
              {"word":"postulation", "memo": "가정, 전제 조건, 선결 조건"},
              {"word":"practical", "memo": "실용적인, 실제적인, 실질상의, 현실적인"},
              {"word":"precipitous", "memo": "가파른, 험한, 깎아지른 듯한"},
              {"word":"predicament", "memo": "곤경, 상태, 경우"},
              {"word":"predicate", "memo": "단정하다"},
              {"word":"premier", "memo": "총리, 최고의, 주지사"},
              {"word":"premise", "memo": "전제, 건물, 토지, 기본, 선행조건"},
              {"word":"prescribe", "memo": "처방하다, 규정하다, 지시하다, 제시하다"},
              {"word":"presumptuous", "memo": "주제넘은, 뻔뻔스러운, 건방진"},
              {"word":"pretentious", "memo": "허세부리는, 자부하는, 자만하는"},
              {"word":"prey", "memo": "먹이, 사냥, 잡아먹다, 희생, 포획"},
              {"word":"price", "memo": "가격, 가격표, 대가, 물가, 가치"},
              {"word":"principal", "memo": "교장, 주요한, 주된, 원금"},
              {"word":"probation", "memo": "보호 관찰, 집행 유예, 시험"},
              {"word":"proceed", "memo": "진행하다, 수익, 계속하다, 추진하다, 나아가다"},
              {"word":"process", "memo": "과정, 공정, 처리, 프로세스, 가공하다"},
              {"word":"procurator", "memo": "대리인, 대행자, 행정 장관"},
              {"word":"prodigal", "memo": "낭비하는, 방탕한, 풍부한"},
              {"word":"progeny", "memo": "자손, 결과, 후계자"},
              {"word":"prone", "memo": "쉬운, 더, 경향, 잘, 취약"},
              {"word":"proponent", "memo": "제안자, 지지자, 발의자"},
              {"word":"propriety", "memo": "예의 바름, 적당, 타당"},
              {"word":"protector", "memo": "보호자, 옹호자, 방어자"},
              {"word":"prove", "memo": "증명하다, 입증하다, 밝혀지다, 드러나다, 판명되다"},
              {"word":"provident", "memo": "선견지명이 있는, 검약한, 절약하는"},
              {"word":"provisional", "memo": "일시적인, 임시의, 잠정적인"},
              {"word":"psychology", "memo": "심리"},
              {"word":"punctuate", "memo": "구두점을 찍다, 중단시키다, 돋보이게 하다"},
              {"word":"purpose", "memo": "목적, 목표, 용도, 의도, 명분"},
              {"word":"quality", "memo": "품질, 질, 특성, 자질, 고급의"},
              {"word":"qualm", "memo": "마음의 꺼림칙함, 양심의 가책, 불안"},
              {"word":"queasy", "memo": "불안한, 불쾌한, 욕지기나는"},
              {"word":"queue", "memo": "줄을 서다"},
              {"word":"quite", "memo": "꽤, 아주, 상당히, 상당수의, 완전히"},
              {"word":"quota", "memo": "쿼터, 할당, 정원, 물량"},
              {"word":"rack", "memo": "짜내다, 선반, …걸이, 침대"},
              {"word":"ragged", "memo": "누더기의, 너덜너덜한"},
              {"word":"raise", "memo": "높이다, 올리다, 오르다, 인상, 제기하다"},
              {"word":"rampant", "memo": "사나운, 만연하는, 뒷발로 일어선"},
              {"word":"ravel", "memo": "…을 얽히게 하다"},
              {"word":"raze", "memo": "지우다, 없애다, 파괴하다"},
              {"word":"readable", "memo": "읽을 수 있는, 판독하기 쉬운, 읽기 쉬운"},
              {"word":"reality", "memo": "현실, 실제, 리얼리티, 사실"},
              {"word":"reap", "memo": "거둬들이다, 이익을 얻다"},
              {"word":"receipt", "memo": "영수증, 증서"},
              {"word":"recognize", "memo": "인정하다, 인식하다, 알다, 알아보다, 인지하다"},
              {"word":"recondite", "memo": "난해한, 심오한, 숨겨진"},
              {"word":"reflect", "memo": "반영하다, 보여준다, 나타내다, 반사하다, 생각하다"},
              {"word":"refractory", "memo": "당할 수 없는, 용해하기 어려운, 완고한"},
              {"word":"region", "memo": "지역, 지방, 지대"},
              {"word":"regretful", "memo": "유감인, 애석하게 여기는, 후회하는"},
              {"word":"reign", "memo": "통치하다, 재임하다, 군림하다, 지배하다, 집권하다"},
              {"word":"remissive", "memo": "관대한, 경감하는, 진정시키는"},
              {"word":"repel", "memo": "쫓아버리다, 격퇴하다, 물리치다"},
              {"word":"reprimand", "memo": "견책, 꾸짖다, 징계"},
              {"word":"repute", "memo": "평판, …이라고 평하다, 간주하다"},
              {"word":"reserve", "memo": "보유하다, 보호지역, 예비, 준비의, 매장량"},
              {"word":"respectable", "memo": "존경할 만한, 훌륭한, 고상한"},
              {"word":"respirator", "memo": "방독 마스크, 인공 호흡 장치, 마스크"},
              {"word":"respite", "memo": "휴식, 일시적 중단, 연기"},
              {"word":"responsible", "memo": "책임이 있는, 담당의, 원인이 되는, 역할을 하다, 요인"},
              {"word":"restless", "memo": "불안한, 쉬지 않는, 안절부절, 초조한, 흥분한"},
              {"word":"retire", "memo": "은퇴하다, 퇴직하다, 퇴역시키다, 퇴임하다, 물러나다"},
              {"word":"revel", "memo": "흥청대다, 떠들썩한 잔치, 레벨"},
              {"word":"revere", "memo": "존경하다"},
              {"word":"reward", "memo": "보상, 대가, 상, 상을 주다, 상금"},
              {"word":"rid", "memo": "없애다, 버리다, 지우다, 제거하다, 벗어나다"},
              {"word":"rise", "memo": "증가하다, 상승하다, 오르다, 늘다, 높아지다"},
              {"word":"roof", "memo": "지붕, 옥상, 천장"},
              {"word":"route", "memo": "길, 방법"},
              {"word":"row", "memo": "줄, 논란, 노젓기, 열, 분쟁"},
              {"word":"rupture", "memo": "파열, 불화, 찢다"},
              {"word":"saga", "memo": "무용담, 중세 북유럽 전설, 모험담"},
              {"word":"sagacious", "memo": "현명한, 영리한, 기민한"},
              {"word":"sailer", "memo": "범선, 배, 돛단배"},
              {"word":"sale", "memo": "판매, 매각, 매매, 세일, 매출"},
              {"word":"salient", "memo": "현저한, 두드러진, 돌출부"},
              {"word":"salon", "memo": "살롱, 미용실, 뷰티숍, 가게"},
              {"word":"salutary", "memo": "유익한, 건강에 좋은, 건전한"},
              {"word":"salvage", "memo": "해난 구조, 구출하다, 침몰선의 인양"},
              {"word":"sanctuary", "memo": "보호구역, 성역, 피난처, 안식처, 신전"},
              {"word":"satisfying", "memo": "만족시키는, 충분한, 납득이 가는"},
              {"word":"savage", "memo": "야만적인, 잔인한, 야생의, 무자비한, 치열한"},
              {"word":"saw", "memo": "봤다, 톱, 톱질하다"},
              {"word":"scrub", "memo": "스크럽, 문지르다, 닦다, 씻다, 제거하다"},
              {"word":"sensible", "memo": "현명한, 합리적인"},
              {"word":"sensory", "memo": "감각의, 지각의"},
              {"word":"sentimental", "memo": "감상적인"},
              {"word":"sentinel", "memo": "보초, 파수, 파수 보다"},
              {"word":"sequester", "memo": "격리하다, 예산 자동 조정"},
              {"word":"serial", "memo": "정기 간행물, 연재물, 일련의"},
              {"word":"shade", "memo": "그늘, 색조, 명암, 차양, 그림자"},
              {"word":"sheer", "memo": "순전히, 순수한, 단순한, 완전히, 전적인"},
              {"word":"shift", "memo": "변화, 전환, 이동하다, 바뀌다, 옮기다"},
              {"word":"shrewd", "memo": "약삭빠른, 영리한, 빈틈없는, 현명한, 능수능란한"},
              {"word":"sign", "memo": "계약하다, 체결하다, 서명하다, 징후, 신호"},
              {"word":"since", "memo": "…이후, …때부터, …이래, 그 후"},
              {"word":"singular", "memo": "단수의, 독특한, 특별한"},
              {"word":"sip", "memo": "마시다, 한 모금"},
              {"word":"skim", "memo": "대충 읽어보다, 걷어내다"},
              {"word":"skyscraper", "memo": "고층건물, 고층빌딩, 마천루"},
              {"word":"slander", "memo": "중상, 중상하다, 욕"},
              {"word":"smack", "memo": "때리다, 치다, 기미, 냄새, 강타하다"},
              {"word":"smother", "memo": "…을 질식시키다, 은폐하다, 짙은 연기"},
              {"word":"snore", "memo": "코를 골다, 코고는 소리"},
              {"word":"snug", "memo": "아늑한, 딱 맞는"},
              {"word":"soar", "memo": "치솟다, 증가하다, 급등하다, 급증하다, 오르다"},
              {"word":"sober", "memo": "냉정한, 술이 깨다, 술을 끊다, 취하지 않은"},
              {"word":"social", "memo": "사회의, 소셜, 인간관계, 집단, 사교적인"},
              {"word":"sometime", "memo": "언제, 조만간, 어느 시점, 이전에, 어느 때"},
              {"word":"soothe", "memo": "진정시키다, 완화하다, 가라앉히다, 덜다, 안심시키다"},
              {"word":"source", "memo": "정보원, 원천, 소스, 공급자, 자료"},
              {"word":"spacious", "memo": "넓은, 널찍한, 공간이 넓은"},
              {"word":"specific", "memo": "특정한, 구체적인, 특별한, 정확히, 상세한"},
              {"word":"specimen", "memo": "표본, 견본"},
              {"word":"spectator", "memo": "관중, 관객, 구경꾼, 방관자"},
              {"word":"sphere", "memo": "영역, 구, 분야, 범위, 천체"},
              {"word":"spouse", "memo": "배우자"},
              {"word":"stall", "memo": "노점, 지연되다, 중단된, 교착, 칸"},
              {"word":"stanch", "memo": "멈추게 하다, 출혈이 멎다, 유출을 멎게 하다"},
              {"word":"stare", "memo": "쳐다보다, 바라보다, 응시하다, 노려보다, 뚫어지게 보다"},
              {"word":"stark", "memo": "완전한, 아주, 완전히, 극명한"},
              {"word":"state", "memo": "국가, 상태, 주, 정부, …을 분명히 말하다"},
              {"word":"stationary", "memo": "정지된, 고정된, 움직이지 않는 사람"},
              {"word":"statue", "memo": "동상, 조각상, 상, 입상"},
              {"word":"steer", "memo": "조종하다, 돌리다, 이끌다, 나아가다"},
              {"word":"strait", "memo": "해협, 곤경, 좁은"},
              {"word":"strategy", "memo": "전략, 방법, 계획"},
              {"word":"stricture", "memo": "비난, 협착, 구속"},
              {"word":"strife", "memo": "분쟁, 투쟁, 갈등, 싸움, 쟁의"},
              {"word":"stumble", "memo": "발견하다, 비틀거리다, 걸림돌, 부진하다"},
              {"word":"sublime", "memo": "숭고한, 멋진"},
              {"word":"subliminal", "memo": "잠재 의식의, 식역하의, 의식하의"},
              {"word":"subsequent", "memo": "그 후의, 차후, 뒤이은, 다음의, 사후"},
              {"word":"subsidy", "memo": "보조금, 기부금, 장려금"},
              {"word":"successful", "memo": "성공한, 잘된, 합격한"},
              {"word":"suit", "memo": "정장, 옷, 소송, 어울리다"},
              {"word":"summon", "memo": "소환하다, 불러내다, 끄집어내다"},
              {"word":"supposition", "memo": "가정, 상상, 추정"},
              {"word":"surprised", "memo": "놀란"},
              {"word":"survey", "memo": "조사하다, 연구하다, 평가하다"},
              {"word":"suspense", "memo": "불안, 걱정, 미정"},
              {"word":"sweat", "memo": "땀을 흘리다, 스웨트, 걱정하다, 초조하다"},
              {"word":"taboo", "memo": "금기, 터부, 금제의"},
              {"word":"tale", "memo": "이야기, 소설"},
              {"word":"tamper", "memo": "간섭하다, 메워 넣는 막대, 주무르다"},
              {"word":"taunt", "memo": "높고 잘 정비된, 비웃다, 악담을 퍼붓다"},
              {"word":"telescope", "memo": "망원경, 현미경, 압축하다"},
              {"word":"temperament", "memo": "기질, 성격"},
              {"word":"tempt", "memo": "유혹하다, 하고 싶은, 끌다, 꾀다"},
              {"word":"tenet", "memo": "주의, 교의, 견해"},
              {"word":"terrible", "memo": "끔찍한, 무서운, 좋지 않은, 엄청난, 약한"},
              {"word":"terrified", "memo": "무서워하는, 오싹한, 겁먹은"},
              {"word":"testimony", "memo": "증언, 증거, 입증"},
              {"word":"thorough", "memo": "철저한, 완전한, 무력 정책"},
              {"word":"timorous", "memo": "겁많은, 소심한, 마음약한"},
              {"word":"tired", "memo": "피곤한, 싫증난"},
              {"word":"tolerable", "memo": "허용할 수 있는, 괜찮은 편인, 견딜 만한"},
              {"word":"tomb", "memo": "무덤"},
              {"word":"torpid", "memo": "둔한, 휴면하고 있는, Oxford대학의 춘계 보트레이스"},
              {"word":"tortuous", "memo": "구불구불한, 비비 꼬인, 비틀린"},
              {"word":"touching", "memo": "…에 관하여, 감동적인, 남의 마음을 움직이는"},
              {"word":"tough", "memo": "힘든, 어려운, 강한, 거친, 터프한"},
              {"word":"tout", "memo": "내세우다, 거론되다, 홍보, 극찬, 꼽히다"},
              {"word":"traction", "memo": "견인, 수축, 전차"},
              {"word":"traitor", "memo": "반역자, 배신자, 매국노"},
              {"word":"trap", "memo": "가두다, 덫, 잡다, 빨아들이다, 과속 감시 장치"},
              {"word":"traverse", "memo": "횡단하다, 가로지르다, 횡단"},
              {"word":"turbid", "memo": "탁한, 자욱한, 혼란된"},
              {"word":"uncover", "memo": "발견하다, 밝히다, 보여주다, 덮개를 열다, 벗다"},
              {"word":"undo", "memo": "원상태로 돌리다, 풀다, 몰락시키다, 열다, 벗다"},
              {"word":"unwilling", "memo": "꺼리는, …하고 싶어하지 않는, 마지못한"},
              {"word":"urban", "memo": "도시의, 도심의"},
              {"word":"vague", "memo": "모호한, 애매한, 희미한"},
              {"word":"valiant", "memo": "용감한, 씩씩한, 단호한"},
              {"word":"vapid", "memo": "김 빠진, 지루한, 활기 없는"},
              {"word":"venal", "memo": "매수할 수 있는, 부패한, 돈으로 좌우되는"},
              {"word":"venom", "memo": "독액, 독, …에 독을 타다"},
              {"word":"venue", "memo": "행위의 현장, 장소, 재판지"},
              {"word":"veracious", "memo": "정직한, 진실한, 정확한"},
              {"word":"vie", "memo": "우열을 다투다, 겨루다, 경쟁하다우열이 없다"},
              {"word":"virtual", "memo": "가상의, 실질적인, 인터넷의"},
              {"word":"vocation", "memo": "직업, 천직, 사명"},
              {"word":"waive", "memo": "포기하다, 보류하다, 미루다"},
              {"word":"wan", "memo": "병약한, 힘없는, 창백한"},
              {"word":"wander", "memo": "돌아다니다, 배회하다, 헤매다, 방랑하다, 산만하다"},
              {"word":"ware", "memo": "도자기류, 상품, 용품"},
              {"word":"warm", "memo": "따뜻한, 온난한, 준비를 하다, 새로운, 데우다"},
              {"word":"watchword", "memo": "암호, 군호, 표어"},
              {"word":"weird", "memo": "이상한, 기묘한, 수상한, 섬뜩한"},
              {"word":"whisper", "memo": "속삭이다, 속삭임, 휘파람 불다"},
              {"word":"wholesome", "memo": "건강에 좋은, 대규모의, 신중한"},
              {"word":"willing", "memo": "기꺼이 하는, …할 의사가 있는, 적극적인, 알맞은"},
              {"word":"wont", "memo": "습관, …하는 습관이 있다, …에 익숙한"},
              {"word":"woo", "memo": "구애하다, 얻으려고 노력하다, 지지를 얻으려고 애쓰다"},
              {"word":"yearn", "memo": "갈망하다, 염원, 그리워하다, 열기"}
            ]
};
